package com.test.lambdacrud.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.google.gson.Gson;
import lombok.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "user")
@Setter
@Getter
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute
    private String name;

    public User(String json) {
        Gson gson = new Gson();
        User tempProduct = gson.fromJson(json, User.class);
        this.userId = tempProduct.userId;
        this.name = tempProduct.name;
    }

    public String toString() {
        return new Gson().toJson(this);
    }
}
